- id: check-python-eol
  name: Check Python version EOL
  entry: py-eol --file
  language: python
  files: '(pyproject\.toml|setup\.py|\.github/workflows/.*\.ya?ml)'
  types: [toml, python, yaml]
  additional_dependencies: ["pyyaml", "packaging"]
