name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox
      - name: Run Nox
        run: nox -s lint test coverage build

      - name: Update eol_data.py
        run: |
          if git diff --quiet HEAD -- eol_data.py; then
            echo "No changes in eol_data.py. Skipping commit and push."
          else
            echo "Changes detected in eol_data.py:"
            git diff eol_data.py

            # Optionally stage the file (if not already staged)
            git add eol_data.py

            # Commit the changes
            git commit -m "Update eol_data.py"

            # Push to the current upstream branch
            git push
          fi
